### ISSUE TITLE
Possible 1.6.7 Release

### ISSUE THREAD

**Issue by allejo** [bovigo/vfsStream#195]
Since I think 2.0 is still a bit away judging by #181, should there be another 1.6.x release with at least the 7.4 compat changes that were made recently?

Is there anything else we'd like to backport from the master branch?

/cc @bovigo/vfsstream

**Comment by jaapio** [comment]
:+1:  for the backport of php 7.4 support

**Comment by kornrunner** [comment]
7.4 support would be great - I'm looking to test everything as early as possible.

**Comment by allejo** [comment]
Do we care about getting Travis tests passing from 5.3 all the way up to 7.4? If so, some work is going to need to be done in the `v1.x` branch.

**Comment by jaapio** [comment]
I think we should drop php 5 support. It is not feasible for us to maintain a agent version of php that nobody should run.

**Comment by allejo** [comment]
Do you mean dropping Travis testing for PHP 5? Because the 1.x branch runs fine with 5, it’s getting it to run on 7 that causes problems because of the PHPUnit versions and deprecations.

We’ve already dropped PHP 5 support for 2.0-dev, which is good. However, we can’t drop support in a point release on the 1.x branch.

**Comment by jaapio** [comment]
If it is an issue to test at php 5.3 just drop it. I understand that it will just work for php 5. Since it does currently. 

People using the current release can just keep using it. It is ok to drop php versions in the same major version since it is not breaking the previous versions. And people's packages won't break since they cannot install it simply.

You are asking for feedback to add support for php 7.4 which could mean that we cannot support php5 any more. I think everyone will understand that we want to move forward. And dropping old php version is a side effect of moving forward. 

It would be a fault to support php 7.4 and not testing at that version.

**Comment by allejo** [comment]
[v1.6.7 tagged and released](https://github.com/bovigo/vfsStream/releases/tag/v1.6.7)
