### ISSUE TITLE
Broken DocBlock

### ISSUE THREAD

**Issue by lee-peuker** [bovigo/vfsStream#206]
org\bovigo\vfs\vfsStreamFile Line 192

```
    /**
     * writes an amount of data
     *
     * Using this method changes the time when the file was last modified.
     *
     * @param   string  $data
     * @return  amount of written bytes
     */
```

@return expects a return type. My code analyzer (psalm) throws an error because it does not know the "class" `amount`.

**Comment by allejo** [comment]
This was fixed in the master branch a while ago in #180; I've pushed an update to the 1.x branch. Since 1.x is in maintenance mode and this doesn't break functionality, this change will have to wait until there is another 1.6.x release (if any). In the meantime, you may use `v1.x-dev` in your composer file.
